name: Staging deployment

on: 
  pull_request:
    types: [labeled]

env:
  DOCKER_IMAGE_NAME: seafrench-azure-ttt
  IMAGE_NAME_URL: docker.pkg.github.com
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: seafrench-ttt-app
  #################################################
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    if: contains(github.event.pull_request.labels.*.name, 'stage')
